### ISSUE TITLE
Creating specification for a problem instance ends in StackOverflow 

### ISSUE THREAD

**Issue by urbanm30** [JuliaPlanners/SymbolicPlanners.jl#2]
Hello, I've been trying to use the package for solving the IPC opt08-strips Sokoban dataset but creating the Specification of the problem throws a StackOverflow error. I have a suspicion that it is because of the metric that is used in the PDDL definition because it worked fine for other domains I tried but none of them had the metric specified. 

Supposedly it's happening at line 64 in src/specifications.jl - the constructor. Do you think there's any way of getting around this? 
Thanks in advance

**Comment by ztangent** [comment]
Thanks for catching this! It looks like I fixed this in the [`refactor` branch](https://github.com/JuliaPlanners/SymbolicPlanners.jl/tree/refactor), but haven't merged it into `master` yet. Are you using the master branch of PDDL.jl (which is v0.2.0), or the registry version (which is v0.1.3)? Because the `refactor` branch is where I'm updating `SymbolicPlanners.jl` to be compatible with the latest PDDL.jl interfaces, so I'd recommend upgrading both.

**Comment by urbanm30** [comment]
So I was able to update the PDDL to v0.2.0 and I can switch between master and refactor branches on SymbolicPlanners.jl. The combination of PDDL v0.2.0 and SymbolicPlanners on master compiles without issues but load_domain and load_problem functions throw the 
MethodError: no method matching parse_problem(::String) 
error. 
The refactor branch on SymbolicPlanners doesn't compile properly with the PDDL v0.2.0. I am  not sure if I'm missing some correct combination of the packages or not.

**Comment by urbanm30** [comment]
Thank you very much! It seems to be working fine with PDDL v0.2.0 and SymbolicPlanners on refactor branch.

**Comment by ztangent** [comment]
As an update, I've now merged the `refactor` branch into `master`, which resolves this issue. Note that the current `master` branch should be used in conjunction with the latest `master` commit to PDDL.jl!
